import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        URL: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        DOMParser: "readonly",
        AbortController: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        console: "readonly",
        performance: "readonly",
        self: "readonly",
        caches: "readonly",
        Request: "readonly",
        Response: "readonly",

        // CDN UMD globals
        pdfjsLib: "readonly",
        mammoth: "readonly",
        Chart: "readonly",
      },
    },
    rules: {
      "no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^(e|_)",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "no-console": "off",
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-prototype-builtins": "off",
      "prefer-const": "warn",
      "no-var": "error",
    },
  },
  {
    ignores: [
      "dist/",
      "build/",
      "node_modules/",
      "app.js",
      "sw.js",
      "tests/",
      ".agents/",
    ],
  },
  // views/index.js re-exports names from every view module and also uses them
  // locally in registerAll(). ESLint flat config does not treat re-exports as
  // local bindings for no-undef, so we list them explicitly here.
  {
    files: ["src/views/index.js"],
    languageOptions: {
      globals: {
        dashboard: "readonly",
        afterDashboard: "readonly",
        dashboardView: "readonly",
        tasks: "readonly",
        afterTasks: "readonly",
        tasksView: "readonly",
        roadmap: "readonly",
        roadmapView: "readonly",
        planner: "readonly",
        plannerView: "readonly",
        assistant: "readonly",
        afterAssistant: "readonly",
        sendChat: "readonly",
        requestStudyPlan: "readonly",
        suggestions: "readonly",
        assistantView: "readonly",
        settings: "readonly",
        afterSettings: "readonly",
        settingsView: "readonly",
        importView: "readonly",
        importPick: "readonly",
        importBind: "readonly",
        importReview: "readonly",
        importReviewBind: "readonly",
        importViewDef: "readonly",
        courses: "readonly",
        coursesView: "readonly",
        library: "readonly",
        libraryView: "readonly",
        helpModal: "readonly",
        docModal: "readonly",
        lessonModal: "readonly",
        courseModal: "readonly",
        eventModal: "readonly",
        readingModal: "readonly",
        modals: "readonly",
      },
    },
  },
];
